### ISSUE TITLE
HeadlessTesting: Playwright support

### ISSUE THREAD

**Issue by headlesstesting** [software-platform/web_test_infra#17]
Hi,

I came across this repo and noticed you mentioned that headlesstesting.com does not fully support the latest Playwright version.

We do however support the latest version. If you could help us with any feedback/struggles you had, please do let me know and we will look into it.

Thanks

**Comment by bootstraponline** [comment]
Hey,

In the research for this project, none of the cloud services supported Playwright master. It's possible an older stable version was supported at one time. The master version crashed as soon as a connection was established. We looked at about 3 services and in the documentation, the versions of playwright supposed were not mentioned. As the API of playwight is evolving quickly, it'd be great to call out what's versions are supported.

**Comment by headlesstesting** [comment]
Thanks for the suggestion. We'll keep a compatibility doc for Playwright https://headlesstesting.com/support/start/playwright.html#compatibility

If you are interested in trying out our service some more, I'm happy to give you some extra free credits.

**Comment by bootstraponline** [comment]
Thanks for updating the doc! Based on the results so far, we have decided to continue to investing in  TestCafe due to cross browser support.

I'm interested in Playwright and will definitely check back once the ecosystem is a bit more mature and [the library is ready](https://aslushnikov.github.io/isplaywrightready/).
